FROM python:3.8.5

WORKDIR /usr/src/app/gradio

COPY . .

RUN pip install --upgrade pip
RUN pip install uwsgi
RUN pip install tensorflow
RUN pip install keras
RUN pip install git+https://github.com/haven-jeon/PyKoSpacing.git
RUN pip install jinja2
RUN pip install gradio
RUN pip install python-docx

CMD ["python", "kospacing.py"]
#CMD ["uwsgi", "--http", ":4000", "--wsgi-file", "kospacing.py"]
#CMD ["uwsgi", "uwsgi.ini"]

EXPOSE 8000